### ISSUE TITLE
Web socket security

### ISSUE THREAD

**Issue by huebl** [ASNeG/OpcUaWebServer#25]
**Is your feature request related to a problem? Please describe.**
The websocket connection does not support security.

**Describe the solution you'd like**
Add security to websocket connection

Includes:

- [x] #59 Rework class WebSocketChannel
- [x] #60 Add SSL Socket to WebSocketGateway
- [x] #61 Add SSL configuration to WebSocketGateway
- [x] #62 Conversion of the test scripts to SSL for WebSocketGateway
- [x] #75 Add SSL configuration to WebSocketServer
- [x] #76 Conversion of the test scripts to SSL for WebSocketServer
- [x] #74 Update documentation
