### ISSUE TITLE
HTTP security

### ISSUE THREAD

**Issue by huebl** [ASNeG/OpcUaWebServer#26]
**Is your feature request related to a problem? Please describe.**
The HTTP connection does not support security

**Describe the solution you'd like**
Add security to HTTP connection

Includes:
- [x] #63 Rework class HttpChannel
- [x] #64 Add SSL configuration to HTTPServer
- [x] #65 Conversion of the test scripts to SSL for HTTPServer
- [x] #74 Documentation
